'use client';
import './globals.css'
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Head from 'next/head';
import {ContextWrapper} from '../context/Context';
import {FilterContextWrapper} from '../context/FilterContext';
import {UserContextWrapper} from '../context/UserContext';
import { getServerSession } from 'next-auth/next';
import { Toaster } from 'react-hot-toast';
import dynamic from 'next/dynamic';
import Header from '../components/Header';
import Navbar from '../components/Navbar';
import Footer from '@/components/Footer';
// const ContactModal = dynamic(()=>import('@/components/ContactModal'));
import Provider from './Provider';
import CartProvider from '../Redux/CartProvider';
import { CartContextWrapper } from '@/context/CartContext';
import {  useLayoutEffect, useState } from 'react';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'E-commerce',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  // const [openContactModal,setOpenContactModal] = useState(false);
  // useLayoutEffect(()=>{
  //   setTimeout(()=>{
  //     setOpenContactModal(true);
  //   },5000)
  // },[])

  return (
    

    
    <html lang="en" className='scroll-smooth'>
      <Head>
      <link rel="preconnect" href="https://fonts.googleapis.com"/>
      <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
      <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,200;0,300;1,200&display=swap" rel="stylesheet"/>
      <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@200;300;400;500;600;700&display=swap" rel="stylesheet"/>
      <link href="https://fonts.googleapis.com/css2?family=Urbanist:wght@200;300;400;500;600;700&display=swap" rel="stylesheet"/>
      </Head>
      <body className={inter.className}>
      <Provider>
        <UserContextWrapper>
          <ContextWrapper>
            <FilterContextWrapper>
              
              <CartProvider>
              <CartContextWrapper>
                <Toaster
                  position='top-center'
                />
                <Header/>
                <Navbar/>
                {children}
                <Footer/>
                </CartContextWrapper>
              </CartProvider>
             
            </FilterContextWrapper>
          
          </ContextWrapper>
        </UserContextWrapper>
      </Provider>
        </body>
    </html>
    
  )
}
